- name: installing system soft
  apt: pkg={{ item }}
  with_items:
    - zsh
    - htop
    - sudo
    - iftop
    - tcpdump
    - wget
    - vim
    - tmux
    - facter
- name: Add admins
  user: name={{ item.user }} shell={{ item.shell }} groups="sudo"
  with_items:
    - "{{ ssh_admins }}"
- name: Add site users
  user: name={{ item.user }} shell={{ item.shell }}
  with_items:
    - "{{ ssh_clients }}"
- include: keys.yml
